let times = ['Flamengo',
      'Palmeiras',
      'São Paulo', 
      'Corinthians',
      'Vasco da Gama',
      'Atlético Mineiro',
      'Grêmio',
      'Internacional',
      'Santos',
      'Fluminense',
      'Cruzeiro',
      'Botafogo',
      'Fortaleza',
      'Athletico Paranaense',
      'Bahia',
      'Ceará',
      'Goiás',
      'Red',
      'Bull',
      'Bragantino',
      'Avaí',
      'Cuiabá']

      console.log(times[0]);